name: Request Map Model

on:
  workflow_dispatch:
    inputs:
      Map:
        description: "Map ID/Model Name/Display Name"
        required: true
        type: text
      Patch:
        description: "Apply a patch to the map. path/to/patch"
        required: false
        default: ""

jobs:
  request-map:
    runs-on: windows-latest
    env:
      MAP: ${{ github.event.inputs.Map }}
      PATCH: ${{ github.event.inputs.Patch }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          .github\scripts\Request-MapModel.ps1 -Map $MAP $(If ($null -ne $PATCH) {"-Patch $PATCH"}) --Verbose
