name: Request Map Model

on:
  workflow_dispatch:
    inputs:
      Map:
        description: 'Map Name, use map id by doing "ID: mapid"'
        required: true
        default: '-'

jobs:
  request-map:
    runs-on: windows-latest
    steps:
      - run: "Write-Host ${{ github.event.inputs.Map }}"
