name: Validate Project Structure

on:
  push:

jobs:
  validate-structure:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: ".github\\scripts\\Validate-Structure.ps1"
